[project]
name = "molecular_qm_models"
dynamic = ["version"]
description = "Molecular QM Models"
requires-python = ">=3.12, <3.13"
dependencies = [
    "pydantic",
    "numpy",
    "simstack",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.version]
source = "vcs"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["molecular_qm_models"]

[project.entry-points."simstack.modules"]
molecular_qm_models = "molecular_qm_models"

[tool.uv.sources]
simstack = { git = "https://github.com/simstack/simstack.git", branch = "main" }

